In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('ragbench_hotpotqa_20260625_025829.csv')
print(df)

              notebook_id                                           question  \
0  ragbench_hotpotqa_0000  Which university did one of the key figures in...
1  ragbench_hotpotqa_0001  Were both Léopold Eyharts and Ulrich Walter a ...
2  ragbench_hotpotqa_0002  Which music group has the most members, DC Tal...
3  ragbench_hotpotqa_0003  Eddie Jemison had a role in the television ser...
4  ragbench_hotpotqa_0004  Consider the band formed in 2015 by JYP Entert...
5  ragbench_hotpotqa_0005  What three categories does income get levied u...
6  ragbench_hotpotqa_0006  What city did the author of "Portraits and Pra...
7  ragbench_hotpotqa_0007  Are both Frank Lloyd and Olivier Assayas Ameri...
8  ragbench_hotpotqa_0008  Which founder of Alcatraz East was born on Mar...
9  ragbench_hotpotqa_0009  Which magazine was first published earlier, Th...

                                           documents  \
0  The Brooklyn Nets are an American professional...
1  Léopold Eyharts (born April 28, 1957) is a Bri...
2  DC Talk (stylized as dc Talk) is a Christian r...
3  Dream School is an American reality television...
4  Wonder Girls () was a South Korean girl group ...
5  The Income Tax Assessment Act 1936 is an act o...
6  Gertrude Stein (February 3, 1874 – July 27, 19...
7  Clouds of Sils Maria (known simply as Sils Mar...
8  John Morgan (born March 31, 1956) is an Americ...
9  The Winter Knights is a children's fantasy nov...

                                            response  \
0  One of the key figures in the American documen...
1  No, only Léopold Eyharts was a General in the ...
2  DC Talk has three members, while Manchester Or...
3                                     March 17, 2015
4  The band formed in 2015 by JYP Entertainment t...
5  Income tax in Australia is levied upon three s...
6  The author of "Portraits and Prayers," Gertrud...
7  No, Frank Lloyd is an American film director, ...
8  John Morgan is the founder of Alcatraz East an...
9  Skeptic magazine was first published earlier i...

                                         response_AI  similarity_score  \
0  Based on the information provided in the docum...            0.7613
1  Theo thông tin được cung cấp, Léopold Eyharts ...            0.8329
2  Based on the information provided, DC Talk has...            0.8373
3  The information provided does not specify the ...            0.4222
4  The band formed in 2015 by JYP Entertainment t...            0.9719
5  The Income Tax Assessment Act 1936 of the Parl...            0.8714
6  Dựa trên thông tin từ nguồn 2, chúng tôi biết ...            0.8648
7  Based on the information provided, Frank Willi...            0.9035
8  The founder of Alcatraz East mentioned in the ...            0.8463
9  Based on the information provided, The Chronic...            0.9152

   true_false  adherence_score_ragbench
0        True                     False
1        True                      True
2        True                      True
3       False                      True
4        True                      True
5        True                      True
6        True                      True
7        True                      True
8        True                      True
9        True                      True

In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', 200)

df = pd.read_csv('ragbench_hotpotqa_20260625_025829.csv', encoding='utf-8-sig')

# Xem từng hàng rõ ràng
df.head(10)

,notebook_id,question,documents,response,response_AI,similarity_score,true_false,adherence_score_ragbench
0,ragbench_hotpotqa_0000,"Which university did one of the key figures in the American documentary film, released in 2015, directed by Malcolm Ingram, pay for, before being drafted 18th overall pick for the New Jersey Nets?","The Brooklyn Nets are an American professional basketball team based in Brooklyn, New York. They are a member of the Atlantic Division of the Eastern Conference in the National Basketball Associat...","One of the key figures in the American documentary film, released in 2015, directed by Malcolm Ingram, played college basketball for Stanford University before being drafted 18th overall pick for ...","Based on the information provided in the document, Jason Collins, one of the key figures in the documentary ""Out to Win"" directed by Malcolm Ingram, played college basketball for Stanford Universi...",0.7613,True,False
1,ragbench_hotpotqa_0001,Were both Léopold Eyharts and Ulrich Walter a General in the French Air Force?,"Léopold Eyharts (born April 28, 1957) is a Brigadier General in the French Air Force, an engineer and ESA astronaut.\n\nThe Armée de l'Air (literally, ""army of the air"") is the name used for the F...","No, only Léopold Eyharts was a General in the French Air Force. Ulrich Walter was a German physicist/engineer and a former DFVLR astronaut, not a General in the French Air Force.","Theo thông tin được cung cấp, Léopold Eyharts là một Đại tá (Brigadier General) trong Không quân Pháp, nhưng Ulrich Hans Walter không được mô tả là một Đại tá trong Không quân Pháp. Thay vào đó, t...",0.8329,True,True
2,ragbench_hotpotqa_0002,"Which music group has the most members, DC Talk, or Manchester Orchestra?","DC Talk (stylized as dc Talk) is a Christian rap and rock trio. The group was formed at Liberty University in Lynchburg, Virginia in 1987 by Toby McKeehan, Michael Tait, and Kevin Max Smith. They ...","DC Talk has three members, while Manchester Orchestra has four members, so Manchester Orchestra has the most members.","Based on the information provided, DC Talk has more members than Manchester Orchestra.\n\nDC Talk is described as a ""Christian rap and rock trio,"" indicating it has three members.\n\nManchester Or...",0.8373,True,True
3,ragbench_hotpotqa_0003,"Eddie Jemison had a role in the television series ""IZombie"", which premiered on what date?","Dream School is an American reality television series on SundanceTV that premiered on October 7, 2013. The series follows fifteen high school dropouts as they are taught by a series of celebrity ""...","March 17, 2015","The information provided does not specify the exact date of the premiere of the television series ""iZombie"". However, it states that ""iZombie"" (stylized as ""iZOMBiE"") is an American television ser...",0.4222,False,True
4,ragbench_hotpotqa_0004,"Consider the band formed in 2015 by JYP Entertainment through the reality show ""Sixteen"". How many tracks are on the reissue of their third album?","Wonder Girls () was a South Korean girl group and band formed by producer Park Jin-young under JYP Entertainment in 2006, which debuted in 2007. The group's final line-up consisted of Yubin, Yeeun...","The band formed in 2015 by JYP Entertainment through the reality show ""Sixteen"" is Twice. The reissue of their third album, ""Twicecoaster: Lane 2"", contains 13 tracks.","The band formed in 2015 by JYP Entertainment through the reality show ""Sixteen"" is Twice. According to the information provided, the reissue of their third extended play (EP), titled ""Twicecoaster...",0.9719,True,True
5,ragbench_hotpotqa_0005,What three categories does income get levied under the Parliament of Australia's tax code?,The Income Tax Assessment Act 1936 is an act of the Parliament of Australia. It is one of the main statutes under which income tax is calculated. The act is gradually being rewritten into the Inco...,"Income tax in Australia is levied upon three sources of income for individual taxpayers: ""personal earnings"" (such as salary and wages), ""business income"" and ""capital gains"".",The Income Tax Assessment Act 1936 of the Parliament of Australia levies income tax on three categories of income for individual taxpayers:\n\n1. Personal earnings: This category includes income s...,0.8714,True,True
6,ragbench_hotpotqa_0006,"What city did the author of ""Portraits and Prayers"" choose to live in after moving to France?","Gertrude Stein (February 3, 1874 – July 27, 1946) was an American novelist, poet, playwright, and art collector. Born in the Allegheny West neighborhood of Pittsburgh, Pennsylvania, and raised in ...","The author of ""Portraits and Prayers,"" Gertrude Stein, chose to live in Paris after moving to France.","Dựa trên thông tin từ nguồn 2, chúng tôi biết Gertrude Stein chuyển đến Paris vào năm 1903 và sống ở đó cho đến khi qua đời. Tuy nhiên, thông tin cụ thể về thành phố mà tác giả của ""Portraits and ...",0.8648,True,True
7,ragbench_hotpotqa_0007,Are both Frank Lloyd and Olivier Assayas American film directors?,"Clouds of Sils Maria (known simply as Sils Maria in some territories) is a 2014 drama film written and directed by Olivier Assayas, and starring Juliette Binoche, Kristen Stewart, and Chloë Grace ...","No, Frank Lloyd is an American film director, while Olivier Assayas is a French film director.","Based on the information provided, Frank William George Lloyd is indeed an American film director, scriptwriter, and producer. However, Olivier Assayas is described as a French film director, scre...",0.9035,True,True
8,ragbench_hotpotqa_0008,"Which founder of Alcatraz East was born on March 31, 1956?","John Morgan (born March 31, 1956) is an American lawyer. He is the founder of the nationwide personal injury law firm Morgan & Morgan.\n\nH. B. ""Bebe"" Lee (December 3, 1916 – March 31, 2013) was a...","John Morgan is the founder of Alcatraz East and was born on March 31, 1956.","The founder of Alcatraz East mentioned in the provided information is John Morgan, who was born on March 31, 1956. According to the sources, John Morgan created and built Alcatraz East, which is a...",0.8463,True,True
9,ragbench_hotpotqa_0009,"Which magazine was first published earlier, The Chronicle of Philanthropy or Skeptic?","The Winter Knights is a children's fantasy novel by Paul Stewart and Chris Riddell, first published in 2005. It is the eighth volume of ""The Edge Chronicles"" and the second of the ""Quint Saga"" tri...","Skeptic magazine was first published earlier in the spring of 1992, while The Chronicle of Philanthropy was founded in 1988. Therefore, The Chronicle of Philanthropy was published earlier.","Based on the information provided, The Chronicle of Philanthropy was first published earlier than Skeptic.\n\nThe relevant details are:\n- The Chronicle of Philanthropy was founded in 1988.\n- Ske...",0.9152,True,True

In [6]:
from IPython.display import display, HTML
display(HTML(df.head(3).to_html()))

In [7]:
import pandas as pd
# Tắt hoàn toàn giới hạn độ dài hiển thị text
pd.set_option('display.max_colwidth', None)

# Đọc file
df = pd.read_csv('ragbench_hotpotqa_20260625_025829.csv')

# Xem hàng số 0 (hàng đầu tiên), chỉ lấy 2 cột bạn cần
df.loc[[0], ['response', 'response_AI']]
row_index = 0  # Chọn hàng muốn xem
print("=== RESPONSE GỐC (Ragbench) ===")
print(df.loc[row_index, 'response'])

print("\n=== RESPONSE AI (Hệ thống của bạn) ===")
print(df.loc[row_index, 'response_AI'])

=== RESPONSE GỐC (Ragbench) ===
One of the key figures in the American documentary film, released in 2015, directed by Malcolm Ingram, played college basketball for Stanford University before being drafted 18th overall pick for the New Jersey Nets.

=== RESPONSE AI (Hệ thống của bạn) ===
Based on the information provided in the document, Jason Collins, one of the key figures in the documentary "Out to Win" directed by Malcolm Ingram, played college basketball for Stanford University. The document states that Jason Collins played college basketball for Stanford University before being drafted 18th overall pick by the Houston Rockets, and later played for the New Jersey Nets (among other teams).

Therefore, the university that Jason Collins paid for, before being drafted 18th overall pick for the New Jersey Nets, was Stanford University.